version: '3.8'

services:
  backend:
    build: ./backend
    image: loganalyze-backend:latest
    container_name: loganalyze_be
    ports:
      - "8000:8000"
    env_file:
      - ./backend/.env
    restart: always

  frontend:
    build: ./frontend
    image: loganalyze-frontend:latest
    container_name: loganalyze_fe
    ports:
      - "80:80"  # Truy cập web bằng http://localhost
    depends_on:
      - backend
    restart: always